# Generated by Django 2.2 on 2021-03-30 17:07

from django.db import migrations


def create_test_objects(apps, schema_editor):
    TestObject = apps.get_model('main', 'TestObject')
    for i in range(9):
        TestObject.objects.create(name='object{}'.format(i+1))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_objects),
    ]
